### ISSUE TITLE
dataset?

### ISSUE THREAD

**Issue by lyxlty** [ankit1997/Fall-Detection-using-CNN#1]
@ankit1997 Hello ! could you tell me about what is your open-dataset in this issue ?  
Thanks!

**Comment by ankit1997** [comment]
Hi , I used MobiFall dataset for this project. You can find more information on https://bmi.teicrete.gr/en/the-mobifall-and-mobiact-datasets-2/

**Comment by lyxlty** [comment]
@ankit1997 Thanks !  but when I python train.py has error and how to solved it?
![image](https://user-images.githubusercontent.com/11659778/49922920-e73be800-feec-11e8-913a-c114cd9d2f1e.png)
sorry, I am deeplearn learing  beginner

**Comment by ankit1997** [comment]
You need to give path to dataset to train it. This will be the path to the MobiFall dataset directory

**Comment by ankit1997** [comment]
@lyxlty closing now
